version: '3.8'

services:
  app:
    image: dynamic-email-generator
    build:
      context: .
    container_name: email-generator-app
    expose:
      - "8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SWAGGER_ENABLED=false
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  nginx:
    image: nginx:latest
    container_name: email-generator-nginx
    ports:
      - "9443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/etc/nginx/ssl
    depends_on:
      - app
