server {
    listen 443 ssl;
    server_name localhost;

    ssl_certificate     /etc/nginx/ssl/selfsigned.crt;
    ssl_certificate_key /etc/nginx/ssl/selfsigned.key;

    location /swagger-ui/ {
        proxy_pass http://email-service:8080/swagger-ui/;
    }

    location /v3/api-docs/ {
        proxy_pass http://email-service:8080/v3/api-docs/;
    }

    location = / {
        return 302 https://$host:9443/swagger-ui/index.html;
    }

    location / {
        proxy_pass http://email-service:8080/;
    }

    error_page 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
